version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=${GROQ_MODEL:-llama-3.3-70b-versatile}
      - AUTOGEN_MAX_TOKENS=${AUTOGEN_MAX_TOKENS:-1024}
      - AUTOGEN_TEMPERATURE=${AUTOGEN_TEMPERATURE:-0.7}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
    volumes:
      - ./backend:/app
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge 